delete method support for memcached
long2ice/fastapi-cache pull request #452
Opened 2024-10-28 15:04 UTC by xodiumx

- Added support for the `clear` method in MemcachedBackend object

2024-11-10 17:11 UTC, vicchi requested changes
@xodiumx Thanks for the PR. In principle I'm happy to merge this for the upcoming `0.3.0` release but there's 2 changes I'd like to see to maintain consistency with both the `Backend` base class and the other backend implementations.

2024-11-10 17:11 UTC, vicchi commented on fastapi_cache/backends/memcached.py
> +        if not key:
The behaviour for the other backends where `clear` is implemented (`inmemory` and `redis`) is to clear the entire cache if no `key` is specified, else to clear only the supplied key, rather than raise an exception (no other backends raise exceptions).

2024-11-10 17:11 UTC, vicchi commented on fastapi_cache/backends/memcached.py
> -    async def clear(self, namespace: Optional[str] = None, key: Optional[str] = None) -> int:
The return type for `clear` in the `Backend` base class is `int` not `bool`. `aiomcache` does return `bool` so this should be cast to an `int` for consistency with both the `Backend` base class and other implementations.

2024-11-11 08:05 UTC, xodiumx commented on fastapi_cache/backends/memcached.py
> +        if not key:
Thanks for the comments, I couldn't find in `aiomcache` removal by `namespace`, but I added full removal by `flush_all` parameter

2024-11-11 08:05 UTC, xodiumx commented on fastapi_cache/backends/memcached.py
> -    async def clear(self, namespace: Optional[str] = None, key: Optional[str] = None) -> int:
Fixed it

2024-11-11 21:29 UTC, vicchi approved these changes

2024-11-11 21:54 UTC, closed without merging

2024-11-11 21:54 UTC, vicchi commented
Manually merged in commit 0b8223c8